
theme: jekyll-theme-minimal
github:
  is_project_page: false

logo: /assets/images/logo.png


site_name: Natalie Johnson Website
title: Natalie's Website
description: A website to see if I can work github pages
navigation:
- Home: index.md
- Figure: pages/figure.md
