
theme: jekyll-theme-minimal
github:
  is_project_page: false

logo: /assets/images/logo.png


site_name: Natalie Johnson Website
title: Website
description: Website test 
nav:
- Home: pages/index.md
- Figure: pages/figure.md
