
theme: jekyll-theme-minimal-mistakes
github:
  is_project_page: false

logo: /assets/images/logo.png

include:
  - _pages
site_name: Natalie Johnson Website
title: Natalie's Website
description: A website to see if I can work github pages
nav:
- Home: index.md
- Figure: pages/figure.md
